### ISSUE TITLE
Fix transition altitude/levels for LFLB

### ISSUE THREAD

**Issue by herver** [vaccfr/vatis-profiles#4]
![image](https://github.com/vaccfr/vatis-profiles/assets/218323/7dbad25a-4f8f-453c-8f99-c51474abce2f)

* Current configuration
https://github.com/vaccfr/vatis-profiles/blob/4bfdfb84d8c85cd270cadf4eb6e21f6018d422bf/vATIS%20Profile%20-%20LFMM.json#L1133-L1143

* Suggested change (if I understand correctly :smile_cat: )
```javascript
{
  "low": 1013, 
  "high": 1040, 
  "altitude": 75
},
{ 
  "low": 940, 
  "high": 1012, 
  "altitude": 85
}
```

**Comment by goulven04** [comment]
Should we rather apply the same configuration as LFKB which a transition altitude of 6,500 feet?
```
{
  "low": 1013,
  "high": 1040,
  "altitude": 70
},
{
  "low": 940,
  "high": 1012,
  "altitude": 80
}
```

I remember that @lsdumas suggested this configuration. Maybe to ask on Discord? :wink:

**Comment by herver** [comment]
Absolutely, I just wanted to get the discussion started.
What I did was simply apply the same basic formula as for other airports... but I know that there are many exceptions :sweat_smile:

**Comment by goulven04** [comment]
80efb5593a70345e78567d7814688cbddcef4631

**Comment by goulven04** [comment]
Transition altitude at LFST is 7000, so transition level should be 80 or 90. 
Transition altitude at LFKB is 6200 ft. Any hint what should be the transition level?

**Comment by lsdumas** [comment]
Hello there 👋🏼

Better late than never... so here is my thought on the matter 😁
 
After a quick listening of LFKB's real ATIS tonight, they had FL80 for transition level with QNH 1008.
My thought  is with TA 6200ft we can round up to next highest thousand and follow the standard rule from there.

This would mean the following for LFKB and LFLB : 

```

{
  "low": 1013,
  "high": 1040,
  "altitude": 70
},
{
  "low": 940,
  "high": 1012,
  "altitude": 80
}

```

And for LFST : 

```

{
  "low": 1013,
  "high": 1040,
  "altitude": 80
},
{
  "low": 940,
  "high": 1012,
  "altitude": 00
}

```

Let me know what you guys think !

**Comment by goulven04** [comment]
Thanks ! 😃 
I guess you meant `90` instead of `00`.
